/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root';
import { Route as PublicLayoutRouteImport } from './app/_publicLayout';
import { Route as AuthLayoutRouteImport } from './app/_authLayout';
import { Route as PublicLayoutIndexRouteImport } from './app/_publicLayout/index';
import { Route as PublicLayoutScholarshipRouteImport } from './app/_publicLayout/scholarship';
import { Route as PublicLayoutPointsRouteImport } from './app/_publicLayout/points';
import { Route as PublicLayoutMembersHorsesRouteImport } from './app/_publicLayout/members-horses';
import { Route as PublicLayoutContactusRouteImport } from './app/_publicLayout/contactus';
import { Route as PublicLayoutCalendarRouteImport } from './app/_publicLayout/calendar';
import { Route as PublicLayoutJoinLayoutRouteImport } from './app/_publicLayout/_joinLayout';
import { Route as AuthLayoutDashboardIndexRouteImport } from './app/_authLayout/dashboard/index';
import { Route as PublicLayoutJoinLayoutJoinIndexRouteImport } from './app/_publicLayout/_joinLayout/join/index';
import { Route as PublicLayoutJoinLayoutJoinIndividualRouteImport } from './app/_publicLayout/_joinLayout/join/individual';
import { Route as PublicLayoutJoinLayoutJoinHorseRouteImport } from './app/_publicLayout/_joinLayout/join/horse';
import { Route as PublicLayoutJoinLayoutJoinBusinessRouteImport } from './app/_publicLayout/_joinLayout/join/business';

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicLayoutIndexRoute = PublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any);
const PublicLayoutScholarshipRoute = PublicLayoutScholarshipRouteImport.update({
  id: '/scholarship',
  path: '/scholarship',
  getParentRoute: () => PublicLayoutRoute,
} as any);
const PublicLayoutPointsRoute = PublicLayoutPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => PublicLayoutRoute,
} as any);
const PublicLayoutMembersHorsesRoute =
  PublicLayoutMembersHorsesRouteImport.update({
    id: '/members-horses',
    path: '/members-horses',
    getParentRoute: () => PublicLayoutRoute,
  } as any);
const PublicLayoutContactusRoute = PublicLayoutContactusRouteImport.update({
  id: '/contactus',
  path: '/contactus',
  getParentRoute: () => PublicLayoutRoute,
} as any);
const PublicLayoutCalendarRoute = PublicLayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PublicLayoutRoute,
} as any);
const PublicLayoutJoinLayoutRoute = PublicLayoutJoinLayoutRouteImport.update({
  id: '/_joinLayout',
  getParentRoute: () => PublicLayoutRoute,
} as any);
const AuthLayoutDashboardIndexRoute =
  AuthLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthLayoutRoute,
  } as any);
const PublicLayoutJoinLayoutJoinIndexRoute =
  PublicLayoutJoinLayoutJoinIndexRouteImport.update({
    id: '/join/',
    path: '/join/',
    getParentRoute: () => PublicLayoutJoinLayoutRoute,
  } as any);
const PublicLayoutJoinLayoutJoinIndividualRoute =
  PublicLayoutJoinLayoutJoinIndividualRouteImport.update({
    id: '/join/individual',
    path: '/join/individual',
    getParentRoute: () => PublicLayoutJoinLayoutRoute,
  } as any);
const PublicLayoutJoinLayoutJoinHorseRoute =
  PublicLayoutJoinLayoutJoinHorseRouteImport.update({
    id: '/join/horse',
    path: '/join/horse',
    getParentRoute: () => PublicLayoutJoinLayoutRoute,
  } as any);
const PublicLayoutJoinLayoutJoinBusinessRoute =
  PublicLayoutJoinLayoutJoinBusinessRouteImport.update({
    id: '/join/business',
    path: '/join/business',
    getParentRoute: () => PublicLayoutJoinLayoutRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/calendar': typeof PublicLayoutCalendarRoute;
  '/contactus': typeof PublicLayoutContactusRoute;
  '/members-horses': typeof PublicLayoutMembersHorsesRoute;
  '/points': typeof PublicLayoutPointsRoute;
  '/scholarship': typeof PublicLayoutScholarshipRoute;
  '/': typeof PublicLayoutIndexRoute;
  '/dashboard': typeof AuthLayoutDashboardIndexRoute;
  '/join/business': typeof PublicLayoutJoinLayoutJoinBusinessRoute;
  '/join/horse': typeof PublicLayoutJoinLayoutJoinHorseRoute;
  '/join/individual': typeof PublicLayoutJoinLayoutJoinIndividualRoute;
  '/join': typeof PublicLayoutJoinLayoutJoinIndexRoute;
}
export interface FileRoutesByTo {
  '/calendar': typeof PublicLayoutCalendarRoute;
  '/contactus': typeof PublicLayoutContactusRoute;
  '/members-horses': typeof PublicLayoutMembersHorsesRoute;
  '/points': typeof PublicLayoutPointsRoute;
  '/scholarship': typeof PublicLayoutScholarshipRoute;
  '/': typeof PublicLayoutIndexRoute;
  '/dashboard': typeof AuthLayoutDashboardIndexRoute;
  '/join/business': typeof PublicLayoutJoinLayoutJoinBusinessRoute;
  '/join/horse': typeof PublicLayoutJoinLayoutJoinHorseRoute;
  '/join/individual': typeof PublicLayoutJoinLayoutJoinIndividualRoute;
  '/join': typeof PublicLayoutJoinLayoutJoinIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authLayout': typeof AuthLayoutRouteWithChildren;
  '/_publicLayout': typeof PublicLayoutRouteWithChildren;
  '/_publicLayout/_joinLayout': typeof PublicLayoutJoinLayoutRouteWithChildren;
  '/_publicLayout/calendar': typeof PublicLayoutCalendarRoute;
  '/_publicLayout/contactus': typeof PublicLayoutContactusRoute;
  '/_publicLayout/members-horses': typeof PublicLayoutMembersHorsesRoute;
  '/_publicLayout/points': typeof PublicLayoutPointsRoute;
  '/_publicLayout/scholarship': typeof PublicLayoutScholarshipRoute;
  '/_publicLayout/': typeof PublicLayoutIndexRoute;
  '/_authLayout/dashboard/': typeof AuthLayoutDashboardIndexRoute;
  '/_publicLayout/_joinLayout/join/business': typeof PublicLayoutJoinLayoutJoinBusinessRoute;
  '/_publicLayout/_joinLayout/join/horse': typeof PublicLayoutJoinLayoutJoinHorseRoute;
  '/_publicLayout/_joinLayout/join/individual': typeof PublicLayoutJoinLayoutJoinIndividualRoute;
  '/_publicLayout/_joinLayout/join/': typeof PublicLayoutJoinLayoutJoinIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/calendar'
    | '/contactus'
    | '/members-horses'
    | '/points'
    | '/scholarship'
    | '/'
    | '/dashboard'
    | '/join/business'
    | '/join/horse'
    | '/join/individual'
    | '/join';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/calendar'
    | '/contactus'
    | '/members-horses'
    | '/points'
    | '/scholarship'
    | '/'
    | '/dashboard'
    | '/join/business'
    | '/join/horse'
    | '/join/individual'
    | '/join';
  id:
    | '__root__'
    | '/_authLayout'
    | '/_publicLayout'
    | '/_publicLayout/_joinLayout'
    | '/_publicLayout/calendar'
    | '/_publicLayout/contactus'
    | '/_publicLayout/members-horses'
    | '/_publicLayout/points'
    | '/_publicLayout/scholarship'
    | '/_publicLayout/'
    | '/_authLayout/dashboard/'
    | '/_publicLayout/_joinLayout/join/business'
    | '/_publicLayout/_joinLayout/join/horse'
    | '/_publicLayout/_joinLayout/join/individual'
    | '/_publicLayout/_joinLayout/join/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren;
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_publicLayout': {
      id: '/_publicLayout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authLayout': {
      id: '/_authLayout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_publicLayout/': {
      id: '/_publicLayout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PublicLayoutIndexRouteImport;
      parentRoute: typeof PublicLayoutRoute;
    };
    '/_publicLayout/scholarship': {
      id: '/_publicLayout/scholarship';
      path: '/scholarship';
      fullPath: '/scholarship';
      preLoaderRoute: typeof PublicLayoutScholarshipRouteImport;
      parentRoute: typeof PublicLayoutRoute;
    };
    '/_publicLayout/points': {
      id: '/_publicLayout/points';
      path: '/points';
      fullPath: '/points';
      preLoaderRoute: typeof PublicLayoutPointsRouteImport;
      parentRoute: typeof PublicLayoutRoute;
    };
    '/_publicLayout/members-horses': {
      id: '/_publicLayout/members-horses';
      path: '/members-horses';
      fullPath: '/members-horses';
      preLoaderRoute: typeof PublicLayoutMembersHorsesRouteImport;
      parentRoute: typeof PublicLayoutRoute;
    };
    '/_publicLayout/contactus': {
      id: '/_publicLayout/contactus';
      path: '/contactus';
      fullPath: '/contactus';
      preLoaderRoute: typeof PublicLayoutContactusRouteImport;
      parentRoute: typeof PublicLayoutRoute;
    };
    '/_publicLayout/calendar': {
      id: '/_publicLayout/calendar';
      path: '/calendar';
      fullPath: '/calendar';
      preLoaderRoute: typeof PublicLayoutCalendarRouteImport;
      parentRoute: typeof PublicLayoutRoute;
    };
    '/_publicLayout/_joinLayout': {
      id: '/_publicLayout/_joinLayout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicLayoutJoinLayoutRouteImport;
      parentRoute: typeof PublicLayoutRoute;
    };
    '/_authLayout/dashboard/': {
      id: '/_authLayout/dashboard/';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthLayoutDashboardIndexRouteImport;
      parentRoute: typeof AuthLayoutRoute;
    };
    '/_publicLayout/_joinLayout/join/': {
      id: '/_publicLayout/_joinLayout/join/';
      path: '/join';
      fullPath: '/join';
      preLoaderRoute: typeof PublicLayoutJoinLayoutJoinIndexRouteImport;
      parentRoute: typeof PublicLayoutJoinLayoutRoute;
    };
    '/_publicLayout/_joinLayout/join/individual': {
      id: '/_publicLayout/_joinLayout/join/individual';
      path: '/join/individual';
      fullPath: '/join/individual';
      preLoaderRoute: typeof PublicLayoutJoinLayoutJoinIndividualRouteImport;
      parentRoute: typeof PublicLayoutJoinLayoutRoute;
    };
    '/_publicLayout/_joinLayout/join/horse': {
      id: '/_publicLayout/_joinLayout/join/horse';
      path: '/join/horse';
      fullPath: '/join/horse';
      preLoaderRoute: typeof PublicLayoutJoinLayoutJoinHorseRouteImport;
      parentRoute: typeof PublicLayoutJoinLayoutRoute;
    };
    '/_publicLayout/_joinLayout/join/business': {
      id: '/_publicLayout/_joinLayout/join/business';
      path: '/join/business';
      fullPath: '/join/business';
      preLoaderRoute: typeof PublicLayoutJoinLayoutJoinBusinessRouteImport;
      parentRoute: typeof PublicLayoutJoinLayoutRoute;
    };
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutDashboardIndexRoute: typeof AuthLayoutDashboardIndexRoute;
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutDashboardIndexRoute: AuthLayoutDashboardIndexRoute,
};

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
);

interface PublicLayoutJoinLayoutRouteChildren {
  PublicLayoutJoinLayoutJoinBusinessRoute: typeof PublicLayoutJoinLayoutJoinBusinessRoute;
  PublicLayoutJoinLayoutJoinHorseRoute: typeof PublicLayoutJoinLayoutJoinHorseRoute;
  PublicLayoutJoinLayoutJoinIndividualRoute: typeof PublicLayoutJoinLayoutJoinIndividualRoute;
  PublicLayoutJoinLayoutJoinIndexRoute: typeof PublicLayoutJoinLayoutJoinIndexRoute;
}

const PublicLayoutJoinLayoutRouteChildren: PublicLayoutJoinLayoutRouteChildren =
  {
    PublicLayoutJoinLayoutJoinBusinessRoute:
      PublicLayoutJoinLayoutJoinBusinessRoute,
    PublicLayoutJoinLayoutJoinHorseRoute: PublicLayoutJoinLayoutJoinHorseRoute,
    PublicLayoutJoinLayoutJoinIndividualRoute:
      PublicLayoutJoinLayoutJoinIndividualRoute,
    PublicLayoutJoinLayoutJoinIndexRoute: PublicLayoutJoinLayoutJoinIndexRoute,
  };

const PublicLayoutJoinLayoutRouteWithChildren =
  PublicLayoutJoinLayoutRoute._addFileChildren(
    PublicLayoutJoinLayoutRouteChildren,
  );

interface PublicLayoutRouteChildren {
  PublicLayoutJoinLayoutRoute: typeof PublicLayoutJoinLayoutRouteWithChildren;
  PublicLayoutCalendarRoute: typeof PublicLayoutCalendarRoute;
  PublicLayoutContactusRoute: typeof PublicLayoutContactusRoute;
  PublicLayoutMembersHorsesRoute: typeof PublicLayoutMembersHorsesRoute;
  PublicLayoutPointsRoute: typeof PublicLayoutPointsRoute;
  PublicLayoutScholarshipRoute: typeof PublicLayoutScholarshipRoute;
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute;
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutJoinLayoutRoute: PublicLayoutJoinLayoutRouteWithChildren,
  PublicLayoutCalendarRoute: PublicLayoutCalendarRoute,
  PublicLayoutContactusRoute: PublicLayoutContactusRoute,
  PublicLayoutMembersHorsesRoute: PublicLayoutMembersHorsesRoute,
  PublicLayoutPointsRoute: PublicLayoutPointsRoute,
  PublicLayoutScholarshipRoute: PublicLayoutScholarshipRoute,
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
};

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
